linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
linters-settings:
  misspell:
    locale: US

run:
  deadline: 1m
